//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid BaseAttck = new Guid("f8302355-e2b6-4b15-8f31-cdb656017bf3");
		public static readonly Guid BaseEnemy = new Guid("b733226d-9e53-4c8f-be29-f8abc9712f69");
		public static readonly Guid BaseEnemyScan = new Guid("fec13c95-8eac-47d6-9475-bca0b4de0018");
		public static readonly Guid SpyEnemy = new Guid("e6fc5f07-8ee4-4a75-9962-ce8dc82f8f7c");

    }
}
